'\" t
.\"     Title: permctl
.\"    Author: [see the "AUTHORS" section]
.\" Generator: DocBook XSL Stylesheets v1.79.1 <http://docbook.sf.net/>
.\"      Date: 05/15/2024
.\"    Manual: \ \&
.\"    Source: \ \&
.\"  Language: English
.\"
.TH "PERMCTL" "8" "05/15/2024" "\ \&" "\ \&"
.\" -----------------------------------------------------------------
.\" * Define some portability stuff
.\" -----------------------------------------------------------------
.\" ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.\" http://bugs.debian.org/507673
.\" http://lists.gnu.org/archive/html/groff/2009-02/msg00013.html
.\" ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.ie \n(.g .ds Aq \(aq
.el       .ds Aq '
.\" -----------------------------------------------------------------
.\" * set default formatting
.\" -----------------------------------------------------------------
.\" disable hyphenation
.nh
.\" disable justification (adjust text to left margin only)
.ad l
.\" -----------------------------------------------------------------
.\" * MAIN CONTENT STARTS HERE *
.\" -----------------------------------------------------------------
.SH "NAME"
permctl \- tool to check and set system wide file permissions
.SH "SYNOPSIS"
.sp
\fBpermctl\fR [OPTIONS] <permission\-files\&...>
.sp
\fBpermctl\fR \-\-system [OPTIONS] <files\&...>
.SH "DESCRIPTION"
.sp
The program \fI/usr/bin/permctl\fR is a tool to check and set file permissions\&. It was previously called chkstat, but has been renamed to better describe its purpose\&.
.sp
permctl can either operate in system mode or on individually specified permission files\&. In system mode, the file \fI/etc/sysconfig/security\fR determines which profile to use and whether to actually apply permission changes\&.
.SH "OPTIONS"
.PP
\fB\-\-system\fR
.RS 4
Run in system mode\&. Parses
\fI/etc/sysconfig/security\fR
to determine which profile / security level to use (\fIPERMISSION_SECURITY\fR) and whether to set or merely warn about permission changes (\fICHECK_PERMISSIONS\fR)\&. In system mode, any non\-option arguments limit the set of files to operate on; i\&.e\&. just as if the \-\-examine option was specified for them\&.
.RE
.PP
\fB\-\-set\fR
.RS 4
Actually apply the file permissions\&. The default is to check and warn only, unless in system mode, where
\fICHECK_PERMISSIONS\fR
specifies the default behavior\&.
.RE
.PP
\fB\-\-warn\fR
.RS 4
Opposite of \-\-set, i\&.e\&. warn only, but don\(cqt make actual changes\&.
.RE
.PP
\fB\-\-noheader\fR
.RS 4
Omit printing the output header lines which describe the configuration files used by permctl\&.
.RE
.PP
\fB\-\-fscaps, \-\-no\-fscaps\fR
.RS 4
Enable or disable use of file based capabilities\&. In system mode the setting of
\fIPERMISSIONS_FSCAPS\fR
determines whether capabilities are applied, when this option is not set\&.
.RE
.PP
\fB\-\-examine <file\&...>\fR
.RS 4
Check permissions for this file instead of all files listed in the permissions files\&. Can appear multiple times\&.
.RE
.PP
\fB\-\-files <filelist\&...>\fR
.RS 4
Check permissions for the files listed in
\fIfilelist\fR
instead of all files listed in the permissions files\&. Can appear multiple times\&. The files must contain the file paths to check, one per line\&.
.RE
.PP
\fB\-\-root <directory>\fR
.RS 4
Check files relative to the specified directory\&.
.RE
.SH "ENVIRONMENT VARIABLES"
.PP
\fBPERMCTL_ALLOW_INSECURE_MODE_IF_NO_PROC\fR
.RS 4
Allow to operate without mounted /proc file system\&. This is an unsafe mode that must only be used in controlled environments where unprivileged users can\(cqt influence file system operation\&.
.RE
.SH "EXIT STATUS"
.sp
permctl returns 1 if any fatal errors have been encountered that prevented it from determining or adjusting file permissions\&. It returns 2 if \fB\-\-warn\fR was given and one or more entries need fixing\&. In all other cases it returns 0\&.
.SH "EXAMPLES"
.sp
.if n \{\
.RS 4
.\}
.nf
permctl \-\-set /usr/share/permissions/permissions /usr/share/permissions/permissions\&.secure
.fi
.if n \{\
.RE
.\}
.sp
Parses the files /usr/share/permissions/permissions and /usr/share/permissions/permissions and sets the file permissions for all files listed there\&.
.sp
.if n \{\
.RS 4
.\}
.nf
permctl \-\-system /bin/ping
.fi
.if n \{\
.RE
.\}
.sp
Run in system mode and only correct permissions of /bin/ping\&.
.SH "SEE ALSO"
.sp
permissions(5)
.SH "COPYRIGHT"
.sp
.if n \{\
.RS 4
.\}
.nf
1996\-2003 SuSE Linux AG, Nuernberg, Germany\&.
2008\-2019 SUSE LINUX Products GmbH
2019\-2024 SUSE Software Solutions Germany GmbH
.fi
.if n \{\
.RE
.\}
.SH "AUTHORS"
.sp
Reinhold Sojer, Ruediger Oertel, Michael Schroeder, Ludwig Nussel
.sp
Useful changes and additions by Tobias Burnus
.sp
Major refactoring by Matthias Gerstner, Malte Kraus
