#!/bin/bash
set -e
shopt -s nullglob
name="`pwd -P`"
name=${name##*/}
name=${name%%.*}
dstdir="package"
src="$PWD"
if [ ! -d "$dstdir/.osc" ]; then
	echo "*** Error: please check out the package:"
	echo "osc branch openSUSE:Factory $name"
	echo "ln -s home\:*\:branches\:*/$name $dstdir"
	exit 1
fi
if [ "`git --no-pager diff --name-only|wc -l`" != '0' -o "`git --no-pager diff --name-only --cached|wc -l`" != 0 ]; then
	echo "*** Error: uncomitted changes"
	echo "run 'git add file' to add files, 'git commit -a' to commit changes"
	exit 1
fi
cd "$dstdir"
echo "osc up"
osc up
cd "$src"
"$src"/obs/mkchanges "$dstdir/$name".changes | tee "$dstdir"/.changes
#test ! -s $dstdir/.changes || git push
for i in *.bz2; do
	/bin/rm -vi "$i"
done
cd "$src"
eval `"$src"/obs/mktar`
mv "$FILENAME" "$dstdir"
cd "$dstdir"
osc add "$FILENAME"
if [ -n "$VERSION" ]; then
	read sourcefile < <(/usr/lib/build/spectool --tag "/source0?/" "$name".spec)
	if [ -n "$sourcefile" ]; then
		sourcefile="${sourcefile/*: /}"
		if [ -e "$sourcefile" ]; then
			osc rm -f "$sourcefile" || true
		fi
	fi
	sed -i -e "0,/^Version: /{s/^\(Version: *\).*/\1$VERSION/;}" "$name".spec
fi
osc vc "$name".changes .changes && rm -f .changes
cd "$src"
if [ -n "`git rev-list remotes/origin/master..HEAD`" ]; then
	pushed=
	if ! grep -q refs/heads/master .git/HEAD; then
		echo "Warning: not on master branch"
	elif read -p "push changes now? (Y/n) "; then
		if [ -z "$REPLY" -o "${REPLY#y}" != "$REPLY" ]; then
			git push && pushed=1 || true
		fi
	fi
	if [ -z "$pushed" ]; then
		echo "*** Warning: changes not pushed!"
	else
		cd "$dstdir"
		osc ci
	fi
fi
